# IMPORT LIB

In [1]:
import numpy as np
import sklearn as sk
import pandas as pd

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head(5)

reason1  reason2  reason3  reason4  Month Value  Day of the week  \
0        0        0        0        1            7                1   
1        0        0        0        0            7                1   
2        0        0        0        1            7                2   
3        1        0        0        0            7                3   
4        0        0        0        1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
cutoff_line = 3.0

In [6]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3,1,0)

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets

In [8]:
targets.sum() / targets.shape[0] 

0.45571428571428574

In [9]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the week','Daily Work Load Average','Distance to Work' ],axis=1)

In [10]:
data_with_targets

reason1  reason2  reason3  reason4  Month Value  Transportation Expense  \
0          0        0        0        1            7                     289   
1          0        0        0        0            7                     118   
2          0        0        0        1            7                     179   
3          1        0        0        0            7                     279   
4          0        0        0        1            7                     289   
..       ...      ...      ...      ...          ...                     ...   
695        1        0        0        0            5                     179   
696        1        0        0        0            5                     225   
697        1        0        0        0            5                     330   
698        0        0        0        1            5                     235   
699        0        0        0        1            5                     291   

     Age  Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0     33               30          0         2     1                      1  
1     50               31          0         1     0                      0  
2     38               31          0         0     0                      0  
3     39               24          0         2     0                      1  
4     33               30          0         2     1                      0  
..   ...              ...        ...       ...   ...                    ...  
695   40               22          1         2     0                      1  
696   28               24          0         1     2                      0  
697   28               25          1         0     0                      1  
698   32               25          1         0     0                      0  
699   40               25          0         1     1                      0  

[700 rows x 12 columns]

In [11]:
unscaled_inputs = data_with_targets.iloc[:,0:14]

In [12]:
from sklearn.preprocessing import StandardScaler
absenteesim_scaler = StandardScaler()

In [13]:
absenteesim_scaler.fit(unscaled_inputs)

StandardScaler()

In [14]:
scaled_inputs = absenteesim_scaler.transform(unscaled_inputs)

In [15]:
scaled_inputs.shape

(700, 12)

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train , x_test ,y_train,y_test = train_test_split(scaled_inputs,targets, train_size = 0.8, random_state =32)

In [18]:
x_test.shape

(140, 12)

In [19]:
y_test.shape

(140,)

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [21]:
reg = LogisticRegression()

In [22]:
reg.fit(x_train,y_train)

LogisticRegression()

In [42]:
reg.score(x_train,y_train)

1.0

# Manually

In [24]:
model_output= reg.predict(x_train)

In [25]:
model_output == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [26]:
np.sum((model_output == y_train))

560

In [27]:
np.sum(True)

1

In [28]:
np.sum(model_output  == y_train) / model_output.shape[0]

1.0

In [29]:
reg.intercept_

array([-0.47459833])

In [30]:
reg.coef_

array([[ 0.3552745 ,  0.03057201,  0.28409406,  0.01464437,  0.03439481,
         0.22730772, -0.06890248,  0.04134039, -0.03631939,  0.17470804,
        -0.08256106,  4.60646276]])

In [31]:
feature_name = unscaled_inputs.columns.values

In [32]:
summary_table = pd.DataFrame(columns=['Feature name'],data = feature_name)


In [33]:
summary_table['Coefficient'] = np.transpose(reg.coef_)

In [34]:
summary_table

Feature name  Coefficient
0                  reason1     0.355274
1                  reason2     0.030572
2                  reason3     0.284094
3                  reason4     0.014644
4              Month Value     0.034395
5   Transportation Expense     0.227308
6                      Age    -0.068902
7          Body Mass Index     0.041340
8                Education    -0.036319
9                 Children     0.174708
10                    Pets    -0.082561
11   Excessive Absenteeism     4.606463

In [35]:
summary_table.index = summary_table.index + 1


In [36]:
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()

In [37]:
summary_table

Feature name  Coefficient
0                Intercept    -0.474598
1                  reason1     0.355274
2                  reason2     0.030572
3                  reason3     0.284094
4                  reason4     0.014644
5              Month Value     0.034395
6   Transportation Expense     0.227308
7                      Age    -0.068902
8          Body Mass Index     0.041340
9                Education    -0.036319
10                Children     0.174708
11                    Pets    -0.082561
12   Excessive Absenteeism     4.606463

In [38]:
###interpret Coef

In [40]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [47]:
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -0.474598    0.622135
1                  reason1     0.355274    1.426572
2                  reason2     0.030572    1.031044
3                  reason3     0.284094    1.328558
4                  reason4     0.014644    1.014752
5              Month Value     0.034395    1.034993
6   Transportation Expense     0.227308    1.255216
7                      Age    -0.068902    0.933418
8          Body Mass Index     0.041340    1.042207
9                Education    -0.036319    0.964332
10                Children     0.174708    1.190898
11                    Pets    -0.082561    0.920755
12   Excessive Absenteeism     4.606463  100.129341

In [45]:
summary_table = summary_table.drop(['Excessive Absenteeism'],axis=0)

KeyError: "['Excessive Absenteeism'] not found in axis"

In [48]:
reg.score(x_test,y_test)

1.0

In [49]:
predicted_proba = reg.predict_proba(x_test)

In [50]:
predicted_proba

array([[0.9953708 , 0.0046292 ],
       [0.0207806 , 0.9792194 ],
       [0.00780586, 0.99219414],
       [0.99550281, 0.00449719],
       [0.99456084, 0.00543916],
       [0.00382876, 0.99617124],
       [0.99157171, 0.00842829],
       [0.99182447, 0.00817553],
       [0.98784711, 0.01215289],
       [0.99221007, 0.00778993],
       [0.9949444 , 0.0050556 ],
       [0.99149637, 0.00850363],
       [0.0051606 , 0.9948394 ],
       [0.00627664, 0.99372336],
       [0.00505022, 0.99494978],
       [0.01335165, 0.98664835],
       [0.99520687, 0.00479313],
       [0.98672696, 0.01327304],
       [0.00986986, 0.99013014],
       [0.98425794, 0.01574206],
       [0.00928933, 0.99071067],
       [0.99182124, 0.00817876],
       [0.9930056 , 0.0069944 ],
       [0.99195788, 0.00804212],
       [0.00934995, 0.99065005],
       [0.99534537, 0.00465463],
       [0.99331431, 0.00668569],
       [0.99362719, 0.00637281],
       [0.00446729, 0.99553271],
       [0.00545461, 0.99454539],
       [0.

In [52]:
predicted_proba[:,1]

array([0.0046292 , 0.9792194 , 0.99219414, 0.00449719, 0.00543916,
       0.99617124, 0.00842829, 0.00817553, 0.01215289, 0.00778993,
       0.0050556 , 0.00850363, 0.9948394 , 0.99372336, 0.99494978,
       0.98664835, 0.00479313, 0.01327304, 0.99013014, 0.01574206,
       0.99071067, 0.00817876, 0.0069944 , 0.00804212, 0.99065005,
       0.00465463, 0.00668569, 0.00637281, 0.99553271, 0.99454539,
       0.99216661, 0.00659684, 0.00460086, 0.00780612, 0.99513769,
       0.00824096, 0.0058444 , 0.00533639, 0.99216661, 0.00528452,
       0.00455611, 0.00850363, 0.00827596, 0.9935603 , 0.99398552,
       0.00533639, 0.01325959, 0.9930377 , 0.0127633 , 0.98804039,
       0.00554899, 0.00588108, 0.01391776, 0.01022654, 0.99027911,
       0.00528452, 0.9934619 , 0.00720202, 0.99340957, 0.00571395,
       0.99447133, 0.99727747, 0.99649291, 0.01301826, 0.0181142 ,
       0.01559062, 0.00618895, 0.98815468, 0.99353691, 0.01471168,
       0.99304358, 0.00549507, 0.01203556, 0.9919343 , 0.99473

In [53]:
### Saving the model

In [55]:
import pickle 

In [56]:
with open('model','wb') as file:
    pickle.dump(reg, file)

In [57]:
with open('scaler','wb') as file:
    pickle.dump(absenteesim_scaler, file)